# -*- coding: utf-8 -*-
"""(Semana 14) Tarea.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10tlJW2Pviqu3HKZhgCrmFTZZugsBAqzE
"""

def calcular_descuento(monto_total, porcentaje_descuento=10):
  """
  Calcula el monto del descuento en una compra.

  Args:
    monto_total: El monto total de la compra.
    porcentaje_descuento: El porcentaje de descuento a aplicar (valor predeterminado es 10).

  Returns:
    El monto del descuento calculado.
  """
  descuento = monto_total * (porcentaje_descuento / 100)
  return descuento

# Llamada a la función con valor predeterminado para el descuento
monto_compra1 = 100
descuento1 = calcular_descuento(monto_compra1)
monto_final1 = monto_compra1 - descuento1

print(f"Compra 1:")
print(f"Monto total: ${monto_compra1:.2f}")
print(f"Descuento: ${descuento1:.2f}")
print(f"Monto final a pagar: ${monto_final1:.2f}")
print("-" * 20)

# Llamada a la función con un porcentaje de descuento específico
monto_compra2 = 250
porcentaje_descuento2 = 20
descuento2 = calcular_descuento(monto_compra2, porcentaje_descuento2)
monto_final2 = monto_compra2 - descuento2

print(f"Compra 2:")
print(f"Monto total: ${monto_compra2:.2f}")
print(f"Porcentaje de descuento: {porcentaje_descuento2}%")
print(f"Descuento: ${descuento2:.2f}")
print(f"Monto final a pagar: ${monto_final2:.2f}")